apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdg
  template:
    metadata:
      labels:
        app: fdg
    spec:
      containers:
      - image: okteto.dev/fdg:latest
        name: fdg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "b6dd1952-1d88-4861-bfa9-9fc024b0d5a3"
        - name: Vless_Path
          value: "/fghyu"
        - name: Vmess_UUID
          value: "b6dd1952-1d88-4861-bfa9-9fc024b0d5a3"
        - name: Vmess_Path
          value: "/dter"
        - name: Share_Path
          value: "/share233"
