apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdfr
  template:
    metadata:
      labels:
        app: sdfr
    spec:
      containers:
      - image: okteto.dev/sdfr:latest
        name: sdfr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "16b1351b-1006-48bb-a006-0c64af4bccdd"
        - name: Vless_Path
          value: "/fgbhety"
        - name: Vmess_UUID
          value: "16b1351b-1006-48bb-a006-0c64af4bccdd"
        - name: Vmess_Path
          value: "/gfhu"
        - name: Share_Path
          value: "/share233"
