apiVersion: apps/v1
kind: Deployment
metadata:
  name: cre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cre
  template:
    metadata:
      labels:
        app: cre
    spec:
      containers:
      - image: okteto.dev/cre:latest
        name: cre
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "5877d424-5750-4d72-ade5-a3468bd49e91"
        - name: Vless_Path
          value: "/adrf"
        - name: Vmess_UUID
          value: "5877d424-5750-4d72-ade5-a3468bd49e91"
        - name: Vmess_Path
          value: "/ewr"
        - name: Share_Path
          value: "/share233"
