apiVersion: apps/v1
kind: Deployment
metadata:
  name: edfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edfe
  template:
    metadata:
      labels:
        app: edfe
    spec:
      containers:
      - image: okteto.dev/edfe:latest
        name: edfe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "239a916a-ad4b-4f43-96ba-467ee8648bdc"
        - name: Vless_Path
          value: "/tryuj"
        - name: Vmess_UUID
          value: "239a916a-ad4b-4f43-96ba-467ee8648bdc"
        - name: Vmess_Path
          value: "/vby"
        - name: Share_Path
          value: "/share233"
